### ISSUE TITLE
Linux python 36 missing

### ISSUE THREAD

**Issue by sannykr** [conda-forge/hiredis-feedstock#7]
I don't think the build is successful in Linux for python 36. Could you please retrigger the build process.

**Comment by sannykr** [comment]
@kwilcox

**Comment by jakirkham** [comment]
Looks like the SSH key used to checkout the feedstock on CircleCI is expired. Most feedstocks use a newer key, but this still has the old one. Trying to readd this feedstock through staged-recipes with PR ( https://github.com/conda-forge/staged-recipes/pull/3934 ) to fix it.

**Comment by jakirkham** [comment]
Reopening until the feedstock actually gets the new SSH key and deploys packages.

**Comment by jakirkham** [comment]
This is now uploaded.
